package net.hqhome.ai.agentz.infrastructor.thread;

import java.util.List;
import net.hqhome.ai.agentz.infrastructor.thread.dataobject.MessageDO;
import net.hqhome.ai.agentz.infrastructor.thread.dataobject.MessageDOExample;
import org.apache.ibatis.annotations.Param;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    long countByExample(MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int deleteByExample(MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int insert(MessageDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int insertSelective(MessageDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    List<MessageDO> selectByExample(MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    MessageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByExampleSelective(@Param("row") MessageDO row, @Param("example") MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByExample(@Param("row") MessageDO row, @Param("example") MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByPrimaryKeySelective(MessageDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByPrimaryKey(MessageDO row);
}