package net.hqhome.ai.agentz.infrastructor.thread;

import java.util.List;
import net.hqhome.ai.agentz.infrastructor.thread.dataobject.ThreadDO;
import net.hqhome.ai.agentz.infrastructor.thread.dataobject.ThreadDOExample;
import org.apache.ibatis.annotations.Param;

public interface ThreadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    long countByExample(ThreadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int deleteByExample(ThreadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int insert(ThreadDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int insertSelective(ThreadDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    List<ThreadDO> selectByExample(ThreadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    ThreadDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByExampleSelective(@Param("row") ThreadDO row, @Param("example") ThreadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByExample(@Param("row") ThreadDO row, @Param("example") ThreadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByPrimaryKeySelective(ThreadDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByPrimaryKey(ThreadDO row);
}