package net.hqhome.ai.agentz.infrastructor.agent.dataobject;

import java.util.Date;

public class AgentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.agent_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.name
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.description
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.type
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.system_message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String systemMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.model_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.model_parameter
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String modelParameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.creator_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.create_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.modified_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.is_deleted
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.id
     *
     * @return the value of agent.id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.id
     *
     * @param id the value for agent.id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.agent_id
     *
     * @return the value of agent.agent_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.agent_id
     *
     * @param agentId the value for agent.agent_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.name
     *
     * @return the value of agent.name
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.name
     *
     * @param name the value for agent.name
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.description
     *
     * @return the value of agent.description
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.description
     *
     * @param description the value for agent.description
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.type
     *
     * @return the value of agent.type
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.type
     *
     * @param type the value for agent.type
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.system_message
     *
     * @return the value of agent.system_message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getSystemMessage() {
        return systemMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.system_message
     *
     * @param systemMessage the value for agent.system_message
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setSystemMessage(String systemMessage) {
        this.systemMessage = systemMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.model_id
     *
     * @return the value of agent.model_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.model_id
     *
     * @param modelId the value for agent.model_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setModelId(String modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.model_parameter
     *
     * @return the value of agent.model_parameter
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getModelParameter() {
        return modelParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.model_parameter
     *
     * @param modelParameter the value for agent.model_parameter
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setModelParameter(String modelParameter) {
        this.modelParameter = modelParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.creator_id
     *
     * @return the value of agent.creator_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.creator_id
     *
     * @param creatorId the value for agent.creator_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.create_time
     *
     * @return the value of agent.create_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.create_time
     *
     * @param createTime the value for agent.create_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.modified_time
     *
     * @return the value of agent.modified_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.modified_time
     *
     * @param modifiedTime the value for agent.modified_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.is_deleted
     *
     * @return the value of agent.is_deleted
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.is_deleted
     *
     * @param isDeleted the value for agent.is_deleted
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}