package net.hqhome.ai.agentz.infrastructor.agent.dataobject;

import java.util.Date;

public class ModelDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.name
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.description
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.type
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.url
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.authorization
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String authorization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.creator_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.create_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.modified_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.is_deleted
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.id
     *
     * @return the value of model.id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.id
     *
     * @param id the value for model.id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_id
     *
     * @return the value of model.model_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_id
     *
     * @param modelId the value for model.model_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setModelId(String modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.name
     *
     * @return the value of model.name
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.name
     *
     * @param name the value for model.name
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.description
     *
     * @return the value of model.description
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.description
     *
     * @param description the value for model.description
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.type
     *
     * @return the value of model.type
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.type
     *
     * @param type the value for model.type
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.url
     *
     * @return the value of model.url
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.url
     *
     * @param url the value for model.url
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model
     *
     * @return the value of model.model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model
     *
     * @param model the value for model.model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.authorization
     *
     * @return the value of model.authorization
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getAuthorization() {
        return authorization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.authorization
     *
     * @param authorization the value for model.authorization
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setAuthorization(String authorization) {
        this.authorization = authorization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.creator_id
     *
     * @return the value of model.creator_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.creator_id
     *
     * @param creatorId the value for model.creator_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.create_time
     *
     * @return the value of model.create_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.create_time
     *
     * @param createTime the value for model.create_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.modified_time
     *
     * @return the value of model.modified_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.modified_time
     *
     * @param modifiedTime the value for model.modified_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.is_deleted
     *
     * @return the value of model.is_deleted
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.is_deleted
     *
     * @param isDeleted the value for model.is_deleted
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}