package net.hqhome.ai.agentz.infrastructor.thread.dataobject;

import java.util.Date;

public class ThreadDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.thread_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.agent_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.user_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.status
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.create_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.modified_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.is_deleted
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.id
     *
     * @return the value of thread.id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.id
     *
     * @param id the value for thread.id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.thread_id
     *
     * @return the value of thread.thread_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.thread_id
     *
     * @param threadId the value for thread.thread_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setThreadId(String threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.agent_id
     *
     * @return the value of thread.agent_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.agent_id
     *
     * @param agentId the value for thread.agent_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.user_id
     *
     * @return the value of thread.user_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.user_id
     *
     * @param userId the value for thread.user_id
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.status
     *
     * @return the value of thread.status
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.status
     *
     * @param status the value for thread.status
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.create_time
     *
     * @return the value of thread.create_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.create_time
     *
     * @param createTime the value for thread.create_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.modified_time
     *
     * @return the value of thread.modified_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.modified_time
     *
     * @param modifiedTime the value for thread.modified_time
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.is_deleted
     *
     * @return the value of thread.is_deleted
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.is_deleted
     *
     * @param isDeleted the value for thread.is_deleted
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}