package net.hqhome.ai.agentz.infrastructor.agent;

import java.util.List;
import net.hqhome.ai.agentz.infrastructor.agent.dataobject.AgentDO;
import net.hqhome.ai.agentz.infrastructor.agent.dataobject.AgentDOExample;
import org.apache.ibatis.annotations.Param;

public interface AgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    long countByExample(AgentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int deleteByExample(AgentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int insert(AgentDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int insertSelective(AgentDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    List<AgentDO> selectByExample(AgentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    AgentDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByExampleSelective(@Param("row") AgentDO row, @Param("example") AgentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByExample(@Param("row") AgentDO row, @Param("example") AgentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByPrimaryKeySelective(AgentDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByPrimaryKey(AgentDO row);
}