package net.hqhome.ai.agentz.infrastructor.agent;

import java.util.List;
import net.hqhome.ai.agentz.infrastructor.agent.dataobject.ModelDO;
import net.hqhome.ai.agentz.infrastructor.agent.dataobject.ModelDOExample;
import org.apache.ibatis.annotations.Param;

public interface ModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    long countByExample(ModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int deleteByExample(ModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int insert(ModelDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int insertSelective(ModelDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    List<ModelDO> selectByExample(ModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    ModelDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByExampleSelective(@Param("row") ModelDO row, @Param("example") ModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByExample(@Param("row") ModelDO row, @Param("example") ModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByPrimaryKeySelective(ModelDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Fri Apr 19 19:32:28 CST 2024
     */
    int updateByPrimaryKey(ModelDO row);
}